---
site_name: Anytype Client
site_url: https://charlesneimog.github.io/anytype-client
repo_url: https://github.com/charlesneimog/anytype-client
theme:
  icon:
    admonition:
      code: simple/python

  name: material
  features: [content.code.copy]
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      accent: light blue
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: assets/any.png
  favicon: assets/any.png
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api/index.md
  - Contributing: contributing.md
  - Examples: examples.md
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # code highlight
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

  # read files
  - pymdownx.snippets
