site_name: Anytype Client
site_url: https://hayduker.github.io/anytype-client
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
nav:
  - Home: index.md
  # - About: about.md
  - API Reference: api/index.md
plugins:
  - search
  - mkdocstrings