site_name: Anytype Client
site_url: https://charlesneimog.github.io/anytype-client
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  logo: assets/any.png
  favicon: assets/any.png
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api/index.md
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings
