[project]
name = "anytype-client" 
version = "1.0.0a1"
description = "A Python Client for Anytype."
readme = "README.md"
authors = [
  {name = "Charles K. Neimog", email = "charlesneimog@outlook.com"},
]
license = {text = "GPL-3.0-or-later"}
dependencies = [
    "requests"
]

[project.optional-dependencies]
zotero = [
    "beautifulsoup4>=4.12,<5",
]
test = [
    "pytest>=8,<9",
]

[project.urls]
"Source Code" = "https://github.com/charlesneimog/anytype-client" 

[tool.setuptools]
packages = ["anytype"]

[tool.black]
line-length = 100
fast = true
